version: '3.3'
services:
    openai-whisper-asr-webservice:
        ports:
            - '9000:9000'
        environment:
            - ASR_MODEL=base
            - ASR_ENGINE=openai_whisper
        image: 'onerahmet/openai-whisper-asr-webservice:latest'
    m1guelpf:
        ports:
            - '8000:8000'
        image: 'ghcr.io/m1guelpf/tinyvector:edge'
        volumes:
            - ./data/tinyvector/:/storage/